[project]
name = "uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas-stubs>=2.2.3.250308",
    "structlog>=25.3.0",
    "pytest>=8.0.0",
    "astroquery>=0.4.10",
    "ruff>=0.11.12",
    "astropy>=7.1.0",
    "openapi-python-client>=0.27.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
